import json
import logging
import re
import time
from typing import List, Dict, Any, Optional

from reasoning_engine_v2 import Hypothesis
from knowledge_graph import KnowledgeGraph, NodeTypes, EdgeTypes

logger = logging.getLogger("agent_debate")

class DebateEngine:
    """Phase 26C: Agent Debate Engine - Multi-Solution Intelligence Layer."""
    def __init__(self, llm: Any, kg: KnowledgeGraph):
        self.llm = llm
        self.kg = kg

    def _call_llm(self, prompt: str) -> str:
        if hasattr(self.llm, "chat") and callable(getattr(self.llm, "chat")):
            return self.llm.chat([{"role": "user", "content": prompt}], max_tokens=2048)
        if callable(self.llm):
            return self.llm(prompt)
        return ""

    def run_debate_and_refine(self, task: str, candidates: List[Hypothesis]) -> List[Hypothesis]:
        """
        PART 2 & 3: Multi-Solution Debate & Cross-Agent Critique
        Executes a multi-agent debate on the given candidates and refines them.
        """
        if not candidates or len(candidates) < 2:
            return candidates

        logger.info(f"Starting debate with {len(candidates)} candidates.")

        # 1. Cross-Agent Critique
        critique_prompt = f"Task: {task}\n\nReview the following candidates generated by the Planner Agent:\n"
        for h in candidates:
            critique_prompt += f"--- Candidate {h.id} (Strategy: {h.strategy_type}) ---\nCode:\n{h.code}\n\n"
        
        critique_prompt += """
You are the 'Alternative Agent' and 'Critic Agent'.
Critique each candidate. Identify flaws, security risks, performance issues, and edge cases.
Provide a concise, harsh critique for each candidate ID.
"""
        critiques = self._call_llm(critique_prompt)

        # 2. Refinement
        refine_prompt = f"""Task: {task}
Here are the candidates and their critiques:
{critiques}

You are the 'Coding Agent'. For each candidate, provide a REFINED version of the code that fixes the flaws mentioned in the critique.
Return exactly a JSON list of dictionaries with keys:
- id: the original candidate id
- refined_code: the improved code
- debate_notes: summary of what was fixed

Respond ONLY with valid JSON.
"""
        refinement_response = self._call_llm(refine_prompt)
        
        refined_data = []
        try:
            match = re.search(r'\[.*\]', refinement_response, re.DOTALL)
            raw_data = match.group(0) if match else refinement_response
            refined_data = json.loads(raw_data)
        except Exception as e:
            logger.error(f"[agent_debate] Failed to parse refined JSON: {e}")
            return candidates

        # Map refinements back to candidates
        refined_map = {item["id"]: item for item in refined_data if "id" in item}
        
        for h in candidates:
            if h.id in refined_map:
                h.code = refined_map[h.id].get("refined_code", h.code)
                h.reflection = refined_map[h.id].get("debate_notes", "Refined via debate.")
                
        # 3. Store Debate Memory to Knowledge Graph
        debate_id = f"debate::{hash(task)}_{int(time.time())}"
        self.kg.add_node(debate_id, NodeTypes.TASK, {"type": "debate", "task": task})
        
        for h in candidates:
            self.kg.add_edge(debate_id, f"hypothesis::{h.id}", EdgeTypes.SIMILAR_TO, {"action": "debated_and_refined"})
            
        self.kg.save()

        return candidates

    def critic_selection(self, task: str, candidates: List[Hypothesis]) -> Hypothesis:
        """
        PART 4: Critic Agent (FINAL DECISION)
        Selects the best solution based on runtime execution scores and code quality.
        """
        if not candidates:
            return None
            
        if len(candidates) == 1:
            return candidates[0]
            
        # Critic uses execution scores to make the final decision
        selection_prompt = f"Task: {task}\n\nWe have executed the refined candidates. Here are the results:\n"
        for h in candidates:
            run_status = h.run_result.get("status") if h.run_result else "Unknown"
            test_pass = h.test_result.get("passed", False) if h.test_result else False
            selection_prompt += f"--- Candidate {h.id} ---\nScore: {h.score}\nRun Status: {run_status}\nTests Passed: {test_pass}\nCode:\n{h.code}\n\n"
            
        selection_prompt += """
You are the 'Critic Agent'. Evaluate correctness, performance, complexity, and reliability based on the execution scores and code.
Select the BEST candidate ID.
Return exactly a JSON dictionary with keys:
- winner_id: string
- reason: string reasoning

Respond ONLY with valid JSON.
"""
        decision_str = self._call_llm(selection_prompt)
        
        # Sort candidates by raw score as fallback
        candidates.sort(key=lambda x: x.score, reverse=True)
        winner_id = candidates[0].id
        reason = "Fallback selection based on highest raw score."

        try:
            match = re.search(r'\{.*\}', decision_str, re.DOTALL)
            if match:
                data = json.loads(match.group(0))
                winner_id = data.get("winner_id", winner_id)
                reason = data.get("reason", reason)
        except Exception as e:
            logger.error(f"[agent_debate] Critic selection parsing failed: {e}")

        winner = next((h for h in candidates if h.id == winner_id), candidates[0])
        
        # PART 5: Debate Memory & Integration with Knowledge Graph
        decision_id = f"decision::{hash(task)}_{int(time.time())}"
        self.kg.add_node(decision_id, NodeTypes.TASK, {"type": "decision", "winner": winner.id, "reason": reason})
        
        for h in candidates:
            status = "accepted" if h.id == winner.id else "rejected"
            self.kg.add_edge(decision_id, f"hypothesis::{h.id}", EdgeTypes.SIMILAR_TO, {"decision": status})
            
        self.kg.save()

        # PART 8: Observability
        logger.info(json.dumps({
            "debate_round": 1,
            "agents": [h.id for h in candidates],
            "winner": winner.id,
            "reason": reason
        }))
        
        return winner
